spring.application.name=planner-backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/planner-dev-db
spring.datasource.username=postgres
spring.datasource.password=password
